### ISSUE TITLE
microapp_target_symbols.ld not updated upon change of TARGET_CONFIG_FILE in Makefile

### ISSUE THREAD

**Issue by martijnvandermarel** [crownstone/crownstone-microapp#9]
### Reproduce bug
1. Change `TARGET_CONFIG_FILE` in Makefile (e.g., change from `target_nrf52840.mk` to `target_nrf52832.mk`)
2. `make clean`
3. `make`
4. `cat include/microapp_target_symbols.ld`

### Expected behaviour
The values in `include/microapp_target_symbols.ld` are expected to be updated based on the new `TARGET_CONFIG_FILE`.

### Current behaviour
The values in `include/microapp_target_symbols.ld` are not updated and instead keep their old values.

**Comment by mrquincle** [comment]
Current workaround is `rm include/microapp_target_symbols.ld`, but will look into it. That target should be regenerated when this variable changes.
